"""
Author      :       Souradeep Bhowmik
Date        :       April 2019
Environment :       Windows 10
Version     :       Python 3.6.2
"""


from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from random import randint
import time
import os

persons = []

options = Options()
options.add_argument('--no-sandbox') # Bypass OS security model
options.add_argument('start-maximized')
options.add_argument('disable-infobars')
options.add_argument("--disable-extensions")
curDir = os.path.dirname(os.path.realpath(__file__)) + "\\" + "chromedriver.exe"
driver = webdriver.Chrome(chrome_options=options, executable_path=curDir)

##########           Open the scrapped names files          ##########
fileReader          = open("first_names.txt", "rt")
firstNameFromFile   = [line.rstrip('\r\n') for line in fileReader]
fileReader          = open("last_names.txt", "rt")
lastNameFromFile    = [line.rstrip('\r\n') for line in fileReader]
fileReader.close()


##########  Iterate through firstnames form scrapped data  ##########
for iterator in range(len(firstNameFromFile)):
    driver.get('https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp')    # Connect to Google account creation website
    driver.implicitly_wait(10)      # 10 seconds wait for all elements to be available

    firstNameElement = driver.find_element_by_name("firstName")
    lastNameElement = driver.find_element_by_name("lastName")
    firstNameElement.send_keys(firstNameFromFile[iterator])
    lastNameElement.send_keys(lastNameFromFile[iterator])
    time.sleep(8)


##########        Google account form filler snippet        ##########
    email = driver.find_element_by_id("username").get_attribute("data-initial-value")       # Grab the autogenerated username suggestion from Google to ensure 100% creation rate
    time.sleep(2)
    if email == "":     # Do this if username suggestion is not generated
        email = firstNameFromFile[iterator].lower()+"."+lastNameFromFile[iterator].lower()+firstNameFromFile[iterator][0]+lastNameFromFile[iterator][0]+str(randint(1980,2010))
        driver.find_element_by_id("username").send_keys(email)
        password = firstNameFromFile[iterator][0].lower() + lastNameFromFile[iterator].upper() + str(randint(1,500))
        driver.find_element_by_name("Passwd").send_keys(password)
        driver.find_element_by_name("ConfirmPasswd").send_keys(password)
        driver.find_element_by_id("accountDetailsNext").click()
        try:            # Check to see if errors were generated upon click of Next
            if driver.find_element_by_class_name("GQ8Pzc").text:
                continue
        except:
            persons.append([firstNameFromFile[iterator], lastNameFromFile[iterator], email, password])
    else:               # Do this if username suggestion is generated
        password = firstNameFromFile[iterator][0].lower() + lastNameFromFile[iterator].upper() + str(randint(100,500))
        driver.find_element_by_name("Passwd").send_keys(password)
        driver.find_element_by_name("ConfirmPasswd").send_keys(password)
        driver.find_element_by_id("accountDetailsNext").click()
        try:            # Check to see if errors were generated upon click of Next
            if driver.find_element_by_class_name("GQ8Pzc").text:
                continue
        except:
            persons.append([firstNameFromFile[iterator], lastNameFromFile[iterator], email, password])

    if len(persons) == 5:       # Break condition after 5 successes, you can keep more
        break
##########      Google account form filler snippet end      ##########

driver.close()